joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

wheels_velocity_controller:
    type: velocity_controllers/JointGroupVelocityController
    joints:
    - rim_back_joint
    - rim_left_joint
    - rim_right_joint
